### ISSUE TITLE
关于算法的post网页失效

### ISSUE THREAD

**Issue by xinyuwufei** [breakds/monster-avengers#10]
大大，你好 咱再tgbus上聊过的loppol
对大大这个算法很感兴趣，但是好像这个网站域名已经失效了？http://blog.breakds.org/armor-up-the-algorithm-behind-monster-hunter-armor-search/

如果大大还有存货的，还望发我一份，让我学习一下🙏

我的email是：me@wufei.me

**Comment by xinyuwufei** [comment]
现在网页能看到了
感谢🙏！

**Comment by ch3rub1m** [comment]
现在网页又失效了 楼上的还有备份吗 能给我发一份不？
