### ISSUE TITLE
网页版配装器发动技能选择错误

### ISSUE THREAD

**Issue by ChienliMa** [breakds/monster-avengers#2]
选择发动技能会有偏差
例子：
我想发动“耳栓”，我必须选择“盾持”添加。
一般上下有一两个位置的随机偏移。

使用osx10.10 ＋ chrome 40.0

**Comment by ChienliMa** [comment]
bug的描述错误。
准确描述：
1. 我选择 `耳栓` 添加，并未添加 `耳栓`
2. 我选择其他技能，如 `达人` 添加，此时添加 `耳栓`
3. 我选择第三个技能添加，此时添加 ``达人`

貌似中间有一个buffer 。`

**Comment by breakds** [comment]
我没法重复这个bug诶。中间倒是没有buffer。可能是javascript里面出了什么问题？
下班以后研究一下。抱歉我对js很不在行。。。

**Comment by breakds** [comment]
添加技能的流程是，首先选择一个技能系统，比如“听觉保护”，然后听觉保护这个系统会被添加到上面。默认发动的技能是耳栓。如果这个系统包含多个技能，就会提供选择，比如对于听觉保护来说，可以选择高级耳栓。

 所以我想确认一下，你说的选择`耳栓`添加，是否指添加“听觉保护”这个系统？

**Comment by ChienliMa** [comment]
是的。我又试了一次。
默认选项是`裂伤`，我选择`听觉保护`添加，结果添加`裂伤`。
然后我选择其他东西他会添加`听觉保护`。
试过几次，结果都是添加`倒数第二次选择的系统`.

**Comment by breakds** [comment]
我仍然无法在本地重复这个bug. 但是根据你的描述,我检查了一下code,确实发现技能面板有一处bug,并且已经修复. 虽然我没有100%的把握这个修复会解决你描述的问题.

我已经update了服务器上的程序,不知道能否麻烦你重新试一下?

非常感谢帮忙找出bug!

**Comment by ChienliMa** [comment]
Now it's perfect! :+1: 
You can close this issue. :smile:

**Comment by breakds** [comment]
多谢指出这个错误! 我自己断然无法发现!
